language: go
go:
    - 1.1
    - 1.2
    - 1.3
    - 1.4
    - 1.5
    - 1.6
    - 1.7
    - 1.8
    - tip
install:
    - echo "Do Nothing, please"
script:
    - go test -v .
after_success:
    - go get gopkg.in/yaml.v2
    - go get github.com/mattn/goveralls
    - go get github.com/axw/gocov/gocov
    - go get code.google.com/p/go.tools/cmd/cover
    - export PATH="$HOME/gopath/bin:$PATH"
    - goveralls -package "github.com/woothee/woothee-go" -repotoken $COVERALLS_TOKEN
env:
    global:
        secure: "SoFKy4rANKsU3UZnMFKS/oDyH4GSefFDDH2pRXV8fF98G9gCwUWYRfdZjanMxdXk5/bRiQ/vvUWnHBvJZyac0NqoV+3lXAApQPf0hB0iFWi6kgIVIlbTNn/6qUrznw5nfwq/yqSiPd9k8lCAl6ai/5IONc/1XSD7izBWrsEWwTw="
